name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Bun
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run linter
      run: bun run lint

    - name: Test CLI functionality
      run: |
        bun run src/index.js --version
        bun run src/index.js --help
        bun run src/index.js config show --format json

  build-dev:
    name: Build Development Binary
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build development binary
      run: bun run build:dev

    - name: Test binary
      run: |
        ./dist/canvas-dev --version
        ./dist/canvas-dev --help

    - name: Upload development binary
      uses: actions/upload-artifact@v4
      with:
        name: canvas-dev-linux
        path: dist/canvas-dev
        retention-days: 7
